version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: hospital
    ports:
      - '3306:3306'

  server:
    build: .
    depends_on:
      - db
    ports:
      - '3001:3001'
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_DATABASE=hospital
